### ISSUE TITLE
Web Client TODO List

### ISSUE THREAD

**Issue by bleutailfly** [arianne/stendhal#254]
#### Graphics

- [x] failsafe image does not work for items *(9832f19fb75)*
- animations:
  - [x] vertical & horizontal alignment of combat animation with entity is off *(d8e09fcad)*
  - combat animations not scaled with entity size (see #682)
  - [x] weapon type combat animations not drawn (a.k.a. *nature*)
  - [x] weapon type combat animations don't rotate
  - [x] animated items not supported *(f1ac6c7d22, dc47776, & af2cd54)*
  - [ ] #674
  - bow combat animation doesn't show for some creatures (centaur king) (see #682)
  - [x] combat animation should use standard natures when attacking at close range with ranged weapon
  - [x] ❗️ "confused" & "shocked" status animations not drawn
- [x] mini map shows interior walls very blurry
- very difficult to understand where player is located on minimap
  - [x] use blue for players *(1dee228)*
  - [x] draw + for players *(6e4e5fe)*
- [x] large corpse sprites are not centered *(26ba9a709a)*
- [x] HP level is sometimes hard to distinguish from HP bar (colors do not contrast) *(f2782471)*
- [x] creature & NPC HP bars need to be offset vertically so they do not block player bar *(1f28afd20)*
- [x] client thinks ugmash sprite is animated (dimensions are maybe not 32x32) *(38b2484658)*
- entity movement in minimap not smooth (low priority) (see #683)
- [ ] #676
- [ ]  #450
- [x] #448
- [x] #493
- [ ] #494
- [x] #491
- [x] #518
- [ ] #517
- [ ] #601

#### Audio

- ~~combat sounds are delayed~~ (not an issue, my browser is just slow ~ AntumDeluge)
- [x] window close sound should only play when [x] is clicked *(8c763fe)*
- [x] #416
- [x] doesn't handle music *(13100af37984)*
- [x] #497
- [x] `DOMException` sometimes occurs when trying to change volume with `/volume` chat command
- [x] #500
- [x] #505

#### Chat

- [x] apostrophes are not drawn in chat log ("you're" appears as "youre") *(48608d9b9a)*
- [ ] #519
- [x] tutorial banner
- [ ] #512
- [x] player level up is not displayed *(ce098c82bc)*
- [x] #488
- [ ] #489
- [x] speech bubble position should compensate for entity size *(5b1f66d4bb)*
- [x] speech bubbles are unreadable when they extend past the right edge of the game window _(e4018e6c9ebb4b6be8ddd346f1c0a66d57d14aa5)_
- [ ] #677
- [x] notification bubbles not flush with bottom of display area _(1699328c3a142bf847f4863a065cd69d09fb59b2)_
- [x] only keep chat bubbles on screen if entity is in viewport area _(613be0d2cee741fdd51eed648633afe46d3b910c)_
- [x] fix keeping chat bubbles in viewport on y axis (currently doesn't take map offset into account like x axis does)

#### UI/Input

- [x] no right-click option to own/leave pet
- [x] cannot pick up/move items that are under self *(d73223c)*
- [x] travel log does not show when quests can be repeated *(ed42040)*
- ~~[ ] changing the size of the main window is not possible~~ (**Note:** modern browsers support zoom)
- [x] need to compensate for corpse size when auto-closing corpse inventory dialog *(f768b97966)*
- [x] ❗️no group/team/party panel
- [x] can't click to remove items from chest, must use drag-and-drop *(7f1781bec2)*
- [x] chest windows don't automatically close after using scroll to teleport *(d03878e0aa)*
- [x] #490
- [x] chat log "copy" context menu option should only copy entire log if no text is highlighted & only highlighted text in case of the opposite *(c8453e03d7)*
- [ ] #675
- [x] need to show "use" cursor for usable items *(8a504d5c48)*
- [x] #583
- [x] #461
- [x] sometimes, character stops after changing direction with arrow keys (key release is being processed after direction change) *(34a28d30d04)*
- [x] clicking on entity is limited to entity dimensions instead of sprite dimensions
- [x] #605
- [x] item touch drag-and-drop doesn't work (see also: #417) *(e00187a)*
- [x] #445 *(6bcc923)*
- [x] clicking notification bubbles should only remove top bubble that was clicked *(fb435f9625)*
- [x] #666
- [x] #487
- [x] #459
- [ ] #458
- [ ] #417
- [ ] #296
- [x] #36
- sidebar/status panel
  - [x] show money *(3e802d1fd4)*
  - [x] show status affects (eating, poisoned, etc.) _(e30dd438a548e5eefb88f016fc46b0e8ab002ed7)_
  - [x] show HP bar *(6edc56ebd1)*
  - [x] show karma bar *(ee09408473f3)*
- [ ] #483
- items that should have "use" context menu options but don't:
  - [x] wedding ring *(22d4ee96d0)*
  - [x] boxes (present, stocking, easter basket, etc.) *(a04a2840ba495a7af13bded6ad1fa1830becd9fe)*
  - [x] ashen holy water *(22d4ee96d0)*
- [x] #506
- [x] #507
- [ ] #509
- [x] #516
- [x] ❗️ dialog windows positions not remembered
- [x] ❗️ #582
- [x] on-screen joystick/d-pad for touch screens (d-pad implemented, joystick WIP)
- [x] needs emoji button & drop-down menu _(f1c2fb85d1235331b6f98497d2d15804ab90d232)_
- [ ] #679
- [x] #591
- [x] #592
- [x] disable pull-down refresh in mobile browsers _(47dea8442de0e7f2eb9f5f59ab895f39b51f0283)_
- [ ] #678
- [ ] #603
- [x] number input fields in settings dialog should default to 0 if content is empty _(4a27bacb529be2c1b866153f3c7a1195c74ec0a8)_
- [ ] #602
- [x] #606

#### Account Creation and Login

- [x] login dialog, when used outside the official website _(833e21faf627d920f0d8129441b11e814222259f)_
- [x] select character dialog, when used outside the official website
- [ ] #681

#### Admin Stuff

- [ ] #680
- [x] using 'inspect' from context menu, the data does not show up in the client msg/game area *(7f26e184a1)*

#### Misc

- [x] #451
- 'reaches' & 'drops to' messages are shown for creatures & NPCs (occurs in testing conditions, doesn't occur in normal gameplay since creatures & NPCs don't gain or lose experience (see #683)

### Old Completed

- [X] its really hard to see item amount in bag, the amount needs to be in black
- [x] when killing a monster the corpse bag does not open up even if there is items in it.
- [x] no sound
- [x] have to drag money out of corpse, have to drag potions out of corpse also
- [x] i can move corpse window closer to bag to unload it, but next kill bag opens up in lower left hand side again.
- [x] i think everything must have to be dragged out of bag, i prolly just ate the potions, just couldn't tell how many i had
- [x] corpse windows do not close when you walk away *(c05d7b5e13)*
- [x] even when changing zones corpse bag is still open all 4 of them.
- [X] web client is showing deniran -4 and it is not released yet. oh i'm on test server
- [x] Admin/GM names are not yellow. (hack used 547f328919, needs improvement)
- [x] Outfit dialog does not retrieve players current outfit when opened.
  - All layers appear to default to lowest index that can be set by player (either 0 or 1).
- [x] No "destroy" option for Admin/GM in entity right-click menu.
  - Partially fixed: "destroy" option added, but doesn't work on items equipped in player inventory.
- [x] Cannot turn off blood/gore. (1458032, f431c4c, 58e16c1, & 690536d)
- [x] Opening menu, then closing with the [x] results in the following message: `Unknown command /. Please type /help to get a list.`
- [x] red targeting ring does not always disappear from player after creature is killed (#484) *(1113ad3b1c)*
- [x] continuous movement does not work
- [x] can't use mouse wheel to change direction (324c1ea80c)
- [x] can't stop auto-walk with direction arrows (fc44e0866f)
- [x] slot emblems are not drawn
- [x] ghostmode is not smooth when walking through collision tiles (a98ebb4)
- [x] rented signs not visible (reported by other player)
- [x] emerald ring image does not update when broken *(0538767610)*
- [x] up/down arrows & mouse wheel scroll entire page on small displays where client is larger than page area (5c4bae8a9bdc291f4de348f869dbffed539ee3e5)
- [x] entities with `ignore_collision` attribute get stuck in collision tiles (a98ebb4)
- [x] no shadows (f9e5bf7 & 9517d33)
- [x] corpses not visible if blood disabled (6cb7e0bfcc)
- [x] doesn't show atk/def xp *(41ac3f571f)*
- [x] a rented sign does not show, but it does have collision - so i right clicked on it and looked to see sign that had been rented - thus finding out why i could not walk there
- [x] teleclickmode does not appear to be working
  - @AntumDeluge: Opened an issue specific to GM commands that don't work: #298
- [x] right clicking on Ivan Abe (NPC) gives me typical browser (firefox) menu, couldn't click out of it, so i saved the 'page' then the ingame menu was able to be used (#206)
- [X] my char is a white rectangle. Might be a sprite image that hasn't been added to web client yet.
- [X] curser does not change when hovering over doors
- [X] context menu after right click does not appear on doors of houses players can buy
- [x] game is jerking heavily
- [x] there don't appear numbers (red or green) over char or creatures
- [x] how is one supposed to exit? closing tab or window seems the only way. Ah, with "Select character" I seem to be able to leave
- [x] cannot move corpses
- [x] skin coloring in outfit dialog is wrong

**Comment by nhnb** [comment]
-The font used for the amount of items in an inventory slot now has a black border. 
- https://stendhalgame.org/client/stendhal.html is the last release on main server. https://stendhalgame.org/testclient/stendhal.html is the night build on test server.

**Comment by nhnb** [comment]
kribble reported in #arianne on 2019-10-30:
[ ] my char is a white rectangle. Might be a sprite image that hasn't been added to web client yet.
[ ] curser does not change when hovering over doors
[ ] context menu after right click does not appear on doors of houses players can buy
[ ] game is jerking heavily
[ ] changing the size of the main window is not possible
[ ] there don't appear numbers (red or green) over char or creatures
[ ] how is one supposed to exit? closing tab or window seems the only way. Ah, with "Select character" I seem to be able to leave

**Comment by tigertoes13** [comment]
* a rented sign does not show, but it does have collision - so i right clicked on it and looked to see sign that had been rented - thus finding out why i could not walk there
* teleclickmode does not appear to be working
* very difficult to understand where player is located on minimap - perhaps should be a vivid purple square
* right clicking on Ivan Abe (NPC) gives me typical browser (firefox) menu, couldn't click out of it, so i saved the 'page' then the ingame menu was able to be used... an additional note on using 'inspect' from that menu, the data does not show up in the client msg/game area
* mini map shows interior walls very blurry
* there is no karma line
* it seems that the animations do not work, ie. sparkles on wells, flames for fires - i will continue to look for other animations that should work but don't

**Comment by tigertoes13** [comment]
i see, now, that this has been closed... why? there is much testing that needs to be done and rectified.

**Comment by tigertoes13** [comment]
oh my goodness, i just saw where i am the one that closed it, i am sorry, this is much different that source forge bug rpts... it is now opened again

**Comment by AntumDeluge** [comment]
- [ ] Admin/GM names are not yellow.

**Comment by AntumDeluge** [comment]
Closing as individual issues have been opened.
