### ISSUE TITLE
Checklist for new outfit system

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#283]
## 💡 Describe your idea

This is a checklist for the new outfit system. Discussion on its items should be done via separate issues.

### Outfit dialog
- [ ] Design an outfit dialog that is easy to use
- [ ] Rework Java outfit dialog to improve usability
- [x] Create outfit dialog in PHP for website character creation
- [x] Create outfit dialog in JavaScript for the webclient

### Database
- [x] Rework outfit storage in database for the website to read
- [x] Update database structure
- [x] Migrate existing outfits

### Drawing
- [x] Draw new outfits on the website
- [x] Draw new outfits on the webclient

### Server
-  [x] Create a mapping from old outfit numbers to new layers and colors
- [x] Update character on login

### Testing
- [ ] ...

**Comment by AntumDeluge** [comment]
Commit da424d4efd should update player 'outfit_ext' attribute on login. I will check it off after I test that it fixes setting outfit with outfit dialog on test server.

**Comment by AntumDeluge** [comment]
Mapping of new layers should be done in 41375f3fdf, but will need to do more testing. TODO: Map eyes color.

**Comment by AntumDeluge** [comment]
Web client now supports setting eyes ( 8b22ccab20 ), mask, & hat ( 95286dfac9 ) layers from outfit dialog.

**Comment by nhnb** [comment]
I think, we are done with the new outfit layers for the upcoming release and this ticket can be closed.
